/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package lukehagar.plexapi.plexapi.models.operations;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import lukehagar.plexapi.plexapi.utils.SpeakeasyMetadata;
import lukehagar.plexapi.plexapi.utils.Utils;


public class GetPlaylistContentsRequest {

    /**
     * the ID of the playlist
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=playlistID")
    private double playlistID;

    /**
     * the metadata type of the item to return
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=type")
    private double type;

    public GetPlaylistContentsRequest(
            double playlistID,
            double type) {
        Utils.checkNotNull(playlistID, "playlistID");
        Utils.checkNotNull(type, "type");
        this.playlistID = playlistID;
        this.type = type;
    }

    /**
     * the ID of the playlist
     */
    public double playlistID() {
        return playlistID;
    }

    /**
     * the metadata type of the item to return
     */
    public double type() {
        return type;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * the ID of the playlist
     */
    public GetPlaylistContentsRequest withPlaylistID(double playlistID) {
        Utils.checkNotNull(playlistID, "playlistID");
        this.playlistID = playlistID;
        return this;
    }

    /**
     * the metadata type of the item to return
     */
    public GetPlaylistContentsRequest withType(double type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetPlaylistContentsRequest other = (GetPlaylistContentsRequest) o;
        return 
            java.util.Objects.deepEquals(this.playlistID, other.playlistID) &&
            java.util.Objects.deepEquals(this.type, other.type);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            playlistID,
            type);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetPlaylistContentsRequest.class,
                "playlistID", playlistID,
                "type", type);
    }
    
    public final static class Builder {
 
        private Double playlistID;
 
        private Double type;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * the ID of the playlist
         */
        public Builder playlistID(double playlistID) {
            Utils.checkNotNull(playlistID, "playlistID");
            this.playlistID = playlistID;
            return this;
        }

        /**
         * the metadata type of the item to return
         */
        public Builder type(double type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }
        
        public GetPlaylistContentsRequest build() {
            return new GetPlaylistContentsRequest(
                playlistID,
                type);
        }
    }
}

