/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetPinResponse {
    /**
     * HTTP response content type for this operation
     */
    
    public String contentType;

    public GetPinResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * HTTP response status code for this operation
     */
    
    public Integer statusCode;

    public GetPinResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    
    public HttpResponse<byte[]> rawResponse;

    public GetPinResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * The Pin
     */
    
    public GetPinResponseBody twoHundredApplicationJsonObject;

    public GetPinResponse withTwoHundredApplicationJsonObject(GetPinResponseBody twoHundredApplicationJsonObject) {
        this.twoHundredApplicationJsonObject = twoHundredApplicationJsonObject;
        return this;
    }
    
    /**
     * X-Plex-Client-Identifier is missing
     */
    
    public GetPinPlexTvResponseBody fourHundredApplicationJsonObject;

    public GetPinResponse withFourHundredApplicationJsonObject(GetPinPlexTvResponseBody fourHundredApplicationJsonObject) {
        this.fourHundredApplicationJsonObject = fourHundredApplicationJsonObject;
        return this;
    }
    
    public GetPinResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode, @JsonProperty("RawResponse") HttpResponse<byte[]> rawResponse) {
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
  }
}
