/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;

/**
 * DvrRequestHandlerSlashGetResponses200
 * 
 * <p>OK
 */
public class DvrRequestHandlerSlashGetResponses200 {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("MediaContainer")
    private Optional<? extends DvrRequestHandlerSlashGetResponses200MediaContainer> mediaContainer;

    @JsonCreator
    public DvrRequestHandlerSlashGetResponses200(
            @JsonProperty("MediaContainer") Optional<? extends DvrRequestHandlerSlashGetResponses200MediaContainer> mediaContainer) {
        Utils.checkNotNull(mediaContainer, "mediaContainer");
        this.mediaContainer = mediaContainer;
    }
    
    public DvrRequestHandlerSlashGetResponses200() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<DvrRequestHandlerSlashGetResponses200MediaContainer> mediaContainer() {
        return (Optional<DvrRequestHandlerSlashGetResponses200MediaContainer>) mediaContainer;
    }

    public static Builder builder() {
        return new Builder();
    }


    public DvrRequestHandlerSlashGetResponses200 withMediaContainer(DvrRequestHandlerSlashGetResponses200MediaContainer mediaContainer) {
        Utils.checkNotNull(mediaContainer, "mediaContainer");
        this.mediaContainer = Optional.ofNullable(mediaContainer);
        return this;
    }


    public DvrRequestHandlerSlashGetResponses200 withMediaContainer(Optional<? extends DvrRequestHandlerSlashGetResponses200MediaContainer> mediaContainer) {
        Utils.checkNotNull(mediaContainer, "mediaContainer");
        this.mediaContainer = mediaContainer;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DvrRequestHandlerSlashGetResponses200 other = (DvrRequestHandlerSlashGetResponses200) o;
        return 
            Utils.enhancedDeepEquals(this.mediaContainer, other.mediaContainer);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            mediaContainer);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DvrRequestHandlerSlashGetResponses200.class,
                "mediaContainer", mediaContainer);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends DvrRequestHandlerSlashGetResponses200MediaContainer> mediaContainer = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder mediaContainer(DvrRequestHandlerSlashGetResponses200MediaContainer mediaContainer) {
            Utils.checkNotNull(mediaContainer, "mediaContainer");
            this.mediaContainer = Optional.ofNullable(mediaContainer);
            return this;
        }

        public Builder mediaContainer(Optional<? extends DvrRequestHandlerSlashGetResponses200MediaContainer> mediaContainer) {
            Utils.checkNotNull(mediaContainer, "mediaContainer");
            this.mediaContainer = mediaContainer;
            return this;
        }

        public DvrRequestHandlerSlashGetResponses200 build() {

            return new DvrRequestHandlerSlashGetResponses200(
                mediaContainer);
        }

    }
}
