/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum MediaContainerWithArtworkType {
    IMAGE("image");

    @JsonValue
    private final String value;

    MediaContainerWithArtworkType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<MediaContainerWithArtworkType> fromValue(String value) {
        for (MediaContainerWithArtworkType o: MediaContainerWithArtworkType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

