/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;

/**
 * MediaContainerWithDecisionMediaContainer
 * 
 * <p>`MediaContainer` is the root element of most Plex API responses. It serves as a generic container for various types of content (Metadata, Hubs, Directories, etc.) and includes pagination information (offset, size, totalSize) when applicable.
 * Common attributes: - identifier: Unique identifier for this container - size: Number of items in this response page - totalSize: Total number of items available (for pagination) - offset: Starting index of this page (for pagination)
 * The container often "hoists" common attributes from its children. For example, if all tracks in a container share the same album title, the `parentTitle` attribute may appear on the MediaContainer rather than being repeated on each track.
 */
public class MediaContainerWithDecisionMediaContainer {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("identifier")
    private Optional<String> identifier;

    /**
     * The offset of where this container page starts among the total objects available. Also provided in the `X-Plex-Container-Start` header.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("offset")
    private Optional<Long> offset;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("size")
    private Optional<Long> size;

    /**
     * The total size of objects available. Also provided in the `X-Plex-Container-Total-Size` header.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("totalSize")
    private Optional<Long> totalSize;

    /**
     * The maximum available bitrate when the decision was rendered.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("availableBandwidth")
    private Optional<Long> availableBandwidth;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("directPlayDecisionCode")
    private Optional<Long> directPlayDecisionCode;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("directPlayDecisionText")
    private Optional<String> directPlayDecisionText;

    /**
     * The overall decision. 1xxx are playback can succeed, 2xxx are a general error (such as insufficient bandwidth), 3xxx are errors in direct play, and 4xxx are errors in transcodes. Same codes are used in all.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("generalDecisionCode")
    private Optional<Long> generalDecisionCode;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("generalDecisionText")
    private Optional<String> generalDecisionText;

    /**
     * The code indicating the status of evaluation of playback when client indicates `hasMDE=1`
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mdeDecisionCode")
    private Optional<Long> mdeDecisionCode;

    /**
     * Descriptive text for the above code
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("mdeDecisionText")
    private Optional<String> mdeDecisionText;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("Metadata")
    private Optional<? extends List<MediaContainerWithDecisionMetadata>> metadata;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("transcodeDecisionCode")
    private Optional<Long> transcodeDecisionCode;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("transcodeDecisionText")
    private Optional<String> transcodeDecisionText;

    @JsonCreator
    public MediaContainerWithDecisionMediaContainer(
            @JsonProperty("identifier") Optional<String> identifier,
            @JsonProperty("offset") Optional<Long> offset,
            @JsonProperty("size") Optional<Long> size,
            @JsonProperty("totalSize") Optional<Long> totalSize,
            @JsonProperty("availableBandwidth") Optional<Long> availableBandwidth,
            @JsonProperty("directPlayDecisionCode") Optional<Long> directPlayDecisionCode,
            @JsonProperty("directPlayDecisionText") Optional<String> directPlayDecisionText,
            @JsonProperty("generalDecisionCode") Optional<Long> generalDecisionCode,
            @JsonProperty("generalDecisionText") Optional<String> generalDecisionText,
            @JsonProperty("mdeDecisionCode") Optional<Long> mdeDecisionCode,
            @JsonProperty("mdeDecisionText") Optional<String> mdeDecisionText,
            @JsonProperty("Metadata") Optional<? extends List<MediaContainerWithDecisionMetadata>> metadata,
            @JsonProperty("transcodeDecisionCode") Optional<Long> transcodeDecisionCode,
            @JsonProperty("transcodeDecisionText") Optional<String> transcodeDecisionText) {
        Utils.checkNotNull(identifier, "identifier");
        Utils.checkNotNull(offset, "offset");
        Utils.checkNotNull(size, "size");
        Utils.checkNotNull(totalSize, "totalSize");
        Utils.checkNotNull(availableBandwidth, "availableBandwidth");
        Utils.checkNotNull(directPlayDecisionCode, "directPlayDecisionCode");
        Utils.checkNotNull(directPlayDecisionText, "directPlayDecisionText");
        Utils.checkNotNull(generalDecisionCode, "generalDecisionCode");
        Utils.checkNotNull(generalDecisionText, "generalDecisionText");
        Utils.checkNotNull(mdeDecisionCode, "mdeDecisionCode");
        Utils.checkNotNull(mdeDecisionText, "mdeDecisionText");
        Utils.checkNotNull(metadata, "metadata");
        Utils.checkNotNull(transcodeDecisionCode, "transcodeDecisionCode");
        Utils.checkNotNull(transcodeDecisionText, "transcodeDecisionText");
        this.identifier = identifier;
        this.offset = offset;
        this.size = size;
        this.totalSize = totalSize;
        this.availableBandwidth = availableBandwidth;
        this.directPlayDecisionCode = directPlayDecisionCode;
        this.directPlayDecisionText = directPlayDecisionText;
        this.generalDecisionCode = generalDecisionCode;
        this.generalDecisionText = generalDecisionText;
        this.mdeDecisionCode = mdeDecisionCode;
        this.mdeDecisionText = mdeDecisionText;
        this.metadata = metadata;
        this.transcodeDecisionCode = transcodeDecisionCode;
        this.transcodeDecisionText = transcodeDecisionText;
    }
    
    public MediaContainerWithDecisionMediaContainer() {
        this(Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty());
    }

    @JsonIgnore
    public Optional<String> identifier() {
        return identifier;
    }

    /**
     * The offset of where this container page starts among the total objects available. Also provided in the `X-Plex-Container-Start` header.
     */
    @JsonIgnore
    public Optional<Long> offset() {
        return offset;
    }

    @JsonIgnore
    public Optional<Long> size() {
        return size;
    }

    /**
     * The total size of objects available. Also provided in the `X-Plex-Container-Total-Size` header.
     */
    @JsonIgnore
    public Optional<Long> totalSize() {
        return totalSize;
    }

    /**
     * The maximum available bitrate when the decision was rendered.
     */
    @JsonIgnore
    public Optional<Long> availableBandwidth() {
        return availableBandwidth;
    }

    @JsonIgnore
    public Optional<Long> directPlayDecisionCode() {
        return directPlayDecisionCode;
    }

    @JsonIgnore
    public Optional<String> directPlayDecisionText() {
        return directPlayDecisionText;
    }

    /**
     * The overall decision. 1xxx are playback can succeed, 2xxx are a general error (such as insufficient bandwidth), 3xxx are errors in direct play, and 4xxx are errors in transcodes. Same codes are used in all.
     */
    @JsonIgnore
    public Optional<Long> generalDecisionCode() {
        return generalDecisionCode;
    }

    @JsonIgnore
    public Optional<String> generalDecisionText() {
        return generalDecisionText;
    }

    /**
     * The code indicating the status of evaluation of playback when client indicates `hasMDE=1`
     */
    @JsonIgnore
    public Optional<Long> mdeDecisionCode() {
        return mdeDecisionCode;
    }

    /**
     * Descriptive text for the above code
     */
    @JsonIgnore
    public Optional<String> mdeDecisionText() {
        return mdeDecisionText;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<MediaContainerWithDecisionMetadata>> metadata() {
        return (Optional<List<MediaContainerWithDecisionMetadata>>) metadata;
    }

    @JsonIgnore
    public Optional<Long> transcodeDecisionCode() {
        return transcodeDecisionCode;
    }

    @JsonIgnore
    public Optional<String> transcodeDecisionText() {
        return transcodeDecisionText;
    }

    public static Builder builder() {
        return new Builder();
    }


    public MediaContainerWithDecisionMediaContainer withIdentifier(String identifier) {
        Utils.checkNotNull(identifier, "identifier");
        this.identifier = Optional.ofNullable(identifier);
        return this;
    }


    public MediaContainerWithDecisionMediaContainer withIdentifier(Optional<String> identifier) {
        Utils.checkNotNull(identifier, "identifier");
        this.identifier = identifier;
        return this;
    }

    /**
     * The offset of where this container page starts among the total objects available. Also provided in the `X-Plex-Container-Start` header.
     */
    public MediaContainerWithDecisionMediaContainer withOffset(long offset) {
        Utils.checkNotNull(offset, "offset");
        this.offset = Optional.ofNullable(offset);
        return this;
    }


    /**
     * The offset of where this container page starts among the total objects available. Also provided in the `X-Plex-Container-Start` header.
     */
    public MediaContainerWithDecisionMediaContainer withOffset(Optional<Long> offset) {
        Utils.checkNotNull(offset, "offset");
        this.offset = offset;
        return this;
    }

    public MediaContainerWithDecisionMediaContainer withSize(long size) {
        Utils.checkNotNull(size, "size");
        this.size = Optional.ofNullable(size);
        return this;
    }


    public MediaContainerWithDecisionMediaContainer withSize(Optional<Long> size) {
        Utils.checkNotNull(size, "size");
        this.size = size;
        return this;
    }

    /**
     * The total size of objects available. Also provided in the `X-Plex-Container-Total-Size` header.
     */
    public MediaContainerWithDecisionMediaContainer withTotalSize(long totalSize) {
        Utils.checkNotNull(totalSize, "totalSize");
        this.totalSize = Optional.ofNullable(totalSize);
        return this;
    }


    /**
     * The total size of objects available. Also provided in the `X-Plex-Container-Total-Size` header.
     */
    public MediaContainerWithDecisionMediaContainer withTotalSize(Optional<Long> totalSize) {
        Utils.checkNotNull(totalSize, "totalSize");
        this.totalSize = totalSize;
        return this;
    }

    /**
     * The maximum available bitrate when the decision was rendered.
     */
    public MediaContainerWithDecisionMediaContainer withAvailableBandwidth(long availableBandwidth) {
        Utils.checkNotNull(availableBandwidth, "availableBandwidth");
        this.availableBandwidth = Optional.ofNullable(availableBandwidth);
        return this;
    }


    /**
     * The maximum available bitrate when the decision was rendered.
     */
    public MediaContainerWithDecisionMediaContainer withAvailableBandwidth(Optional<Long> availableBandwidth) {
        Utils.checkNotNull(availableBandwidth, "availableBandwidth");
        this.availableBandwidth = availableBandwidth;
        return this;
    }

    public MediaContainerWithDecisionMediaContainer withDirectPlayDecisionCode(long directPlayDecisionCode) {
        Utils.checkNotNull(directPlayDecisionCode, "directPlayDecisionCode");
        this.directPlayDecisionCode = Optional.ofNullable(directPlayDecisionCode);
        return this;
    }


    public MediaContainerWithDecisionMediaContainer withDirectPlayDecisionCode(Optional<Long> directPlayDecisionCode) {
        Utils.checkNotNull(directPlayDecisionCode, "directPlayDecisionCode");
        this.directPlayDecisionCode = directPlayDecisionCode;
        return this;
    }

    public MediaContainerWithDecisionMediaContainer withDirectPlayDecisionText(String directPlayDecisionText) {
        Utils.checkNotNull(directPlayDecisionText, "directPlayDecisionText");
        this.directPlayDecisionText = Optional.ofNullable(directPlayDecisionText);
        return this;
    }


    public MediaContainerWithDecisionMediaContainer withDirectPlayDecisionText(Optional<String> directPlayDecisionText) {
        Utils.checkNotNull(directPlayDecisionText, "directPlayDecisionText");
        this.directPlayDecisionText = directPlayDecisionText;
        return this;
    }

    /**
     * The overall decision. 1xxx are playback can succeed, 2xxx are a general error (such as insufficient bandwidth), 3xxx are errors in direct play, and 4xxx are errors in transcodes. Same codes are used in all.
     */
    public MediaContainerWithDecisionMediaContainer withGeneralDecisionCode(long generalDecisionCode) {
        Utils.checkNotNull(generalDecisionCode, "generalDecisionCode");
        this.generalDecisionCode = Optional.ofNullable(generalDecisionCode);
        return this;
    }


    /**
     * The overall decision. 1xxx are playback can succeed, 2xxx are a general error (such as insufficient bandwidth), 3xxx are errors in direct play, and 4xxx are errors in transcodes. Same codes are used in all.
     */
    public MediaContainerWithDecisionMediaContainer withGeneralDecisionCode(Optional<Long> generalDecisionCode) {
        Utils.checkNotNull(generalDecisionCode, "generalDecisionCode");
        this.generalDecisionCode = generalDecisionCode;
        return this;
    }

    public MediaContainerWithDecisionMediaContainer withGeneralDecisionText(String generalDecisionText) {
        Utils.checkNotNull(generalDecisionText, "generalDecisionText");
        this.generalDecisionText = Optional.ofNullable(generalDecisionText);
        return this;
    }


    public MediaContainerWithDecisionMediaContainer withGeneralDecisionText(Optional<String> generalDecisionText) {
        Utils.checkNotNull(generalDecisionText, "generalDecisionText");
        this.generalDecisionText = generalDecisionText;
        return this;
    }

    /**
     * The code indicating the status of evaluation of playback when client indicates `hasMDE=1`
     */
    public MediaContainerWithDecisionMediaContainer withMdeDecisionCode(long mdeDecisionCode) {
        Utils.checkNotNull(mdeDecisionCode, "mdeDecisionCode");
        this.mdeDecisionCode = Optional.ofNullable(mdeDecisionCode);
        return this;
    }


    /**
     * The code indicating the status of evaluation of playback when client indicates `hasMDE=1`
     */
    public MediaContainerWithDecisionMediaContainer withMdeDecisionCode(Optional<Long> mdeDecisionCode) {
        Utils.checkNotNull(mdeDecisionCode, "mdeDecisionCode");
        this.mdeDecisionCode = mdeDecisionCode;
        return this;
    }

    /**
     * Descriptive text for the above code
     */
    public MediaContainerWithDecisionMediaContainer withMdeDecisionText(String mdeDecisionText) {
        Utils.checkNotNull(mdeDecisionText, "mdeDecisionText");
        this.mdeDecisionText = Optional.ofNullable(mdeDecisionText);
        return this;
    }


    /**
     * Descriptive text for the above code
     */
    public MediaContainerWithDecisionMediaContainer withMdeDecisionText(Optional<String> mdeDecisionText) {
        Utils.checkNotNull(mdeDecisionText, "mdeDecisionText");
        this.mdeDecisionText = mdeDecisionText;
        return this;
    }

    public MediaContainerWithDecisionMediaContainer withMetadata(List<MediaContainerWithDecisionMetadata> metadata) {
        Utils.checkNotNull(metadata, "metadata");
        this.metadata = Optional.ofNullable(metadata);
        return this;
    }


    public MediaContainerWithDecisionMediaContainer withMetadata(Optional<? extends List<MediaContainerWithDecisionMetadata>> metadata) {
        Utils.checkNotNull(metadata, "metadata");
        this.metadata = metadata;
        return this;
    }

    public MediaContainerWithDecisionMediaContainer withTranscodeDecisionCode(long transcodeDecisionCode) {
        Utils.checkNotNull(transcodeDecisionCode, "transcodeDecisionCode");
        this.transcodeDecisionCode = Optional.ofNullable(transcodeDecisionCode);
        return this;
    }


    public MediaContainerWithDecisionMediaContainer withTranscodeDecisionCode(Optional<Long> transcodeDecisionCode) {
        Utils.checkNotNull(transcodeDecisionCode, "transcodeDecisionCode");
        this.transcodeDecisionCode = transcodeDecisionCode;
        return this;
    }

    public MediaContainerWithDecisionMediaContainer withTranscodeDecisionText(String transcodeDecisionText) {
        Utils.checkNotNull(transcodeDecisionText, "transcodeDecisionText");
        this.transcodeDecisionText = Optional.ofNullable(transcodeDecisionText);
        return this;
    }


    public MediaContainerWithDecisionMediaContainer withTranscodeDecisionText(Optional<String> transcodeDecisionText) {
        Utils.checkNotNull(transcodeDecisionText, "transcodeDecisionText");
        this.transcodeDecisionText = transcodeDecisionText;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MediaContainerWithDecisionMediaContainer other = (MediaContainerWithDecisionMediaContainer) o;
        return 
            Utils.enhancedDeepEquals(this.identifier, other.identifier) &&
            Utils.enhancedDeepEquals(this.offset, other.offset) &&
            Utils.enhancedDeepEquals(this.size, other.size) &&
            Utils.enhancedDeepEquals(this.totalSize, other.totalSize) &&
            Utils.enhancedDeepEquals(this.availableBandwidth, other.availableBandwidth) &&
            Utils.enhancedDeepEquals(this.directPlayDecisionCode, other.directPlayDecisionCode) &&
            Utils.enhancedDeepEquals(this.directPlayDecisionText, other.directPlayDecisionText) &&
            Utils.enhancedDeepEquals(this.generalDecisionCode, other.generalDecisionCode) &&
            Utils.enhancedDeepEquals(this.generalDecisionText, other.generalDecisionText) &&
            Utils.enhancedDeepEquals(this.mdeDecisionCode, other.mdeDecisionCode) &&
            Utils.enhancedDeepEquals(this.mdeDecisionText, other.mdeDecisionText) &&
            Utils.enhancedDeepEquals(this.metadata, other.metadata) &&
            Utils.enhancedDeepEquals(this.transcodeDecisionCode, other.transcodeDecisionCode) &&
            Utils.enhancedDeepEquals(this.transcodeDecisionText, other.transcodeDecisionText);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            identifier, offset, size,
            totalSize, availableBandwidth, directPlayDecisionCode,
            directPlayDecisionText, generalDecisionCode, generalDecisionText,
            mdeDecisionCode, mdeDecisionText, metadata,
            transcodeDecisionCode, transcodeDecisionText);
    }
    
    @Override
    public String toString() {
        return Utils.toString(MediaContainerWithDecisionMediaContainer.class,
                "identifier", identifier,
                "offset", offset,
                "size", size,
                "totalSize", totalSize,
                "availableBandwidth", availableBandwidth,
                "directPlayDecisionCode", directPlayDecisionCode,
                "directPlayDecisionText", directPlayDecisionText,
                "generalDecisionCode", generalDecisionCode,
                "generalDecisionText", generalDecisionText,
                "mdeDecisionCode", mdeDecisionCode,
                "mdeDecisionText", mdeDecisionText,
                "metadata", metadata,
                "transcodeDecisionCode", transcodeDecisionCode,
                "transcodeDecisionText", transcodeDecisionText);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> identifier = Optional.empty();

        private Optional<Long> offset = Optional.empty();

        private Optional<Long> size = Optional.empty();

        private Optional<Long> totalSize = Optional.empty();

        private Optional<Long> availableBandwidth = Optional.empty();

        private Optional<Long> directPlayDecisionCode = Optional.empty();

        private Optional<String> directPlayDecisionText = Optional.empty();

        private Optional<Long> generalDecisionCode = Optional.empty();

        private Optional<String> generalDecisionText = Optional.empty();

        private Optional<Long> mdeDecisionCode = Optional.empty();

        private Optional<String> mdeDecisionText = Optional.empty();

        private Optional<? extends List<MediaContainerWithDecisionMetadata>> metadata = Optional.empty();

        private Optional<Long> transcodeDecisionCode = Optional.empty();

        private Optional<String> transcodeDecisionText = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder identifier(String identifier) {
            Utils.checkNotNull(identifier, "identifier");
            this.identifier = Optional.ofNullable(identifier);
            return this;
        }

        public Builder identifier(Optional<String> identifier) {
            Utils.checkNotNull(identifier, "identifier");
            this.identifier = identifier;
            return this;
        }


        /**
         * The offset of where this container page starts among the total objects available. Also provided in the `X-Plex-Container-Start` header.
         */
        public Builder offset(long offset) {
            Utils.checkNotNull(offset, "offset");
            this.offset = Optional.ofNullable(offset);
            return this;
        }

        /**
         * The offset of where this container page starts among the total objects available. Also provided in the `X-Plex-Container-Start` header.
         */
        public Builder offset(Optional<Long> offset) {
            Utils.checkNotNull(offset, "offset");
            this.offset = offset;
            return this;
        }


        public Builder size(long size) {
            Utils.checkNotNull(size, "size");
            this.size = Optional.ofNullable(size);
            return this;
        }

        public Builder size(Optional<Long> size) {
            Utils.checkNotNull(size, "size");
            this.size = size;
            return this;
        }


        /**
         * The total size of objects available. Also provided in the `X-Plex-Container-Total-Size` header.
         */
        public Builder totalSize(long totalSize) {
            Utils.checkNotNull(totalSize, "totalSize");
            this.totalSize = Optional.ofNullable(totalSize);
            return this;
        }

        /**
         * The total size of objects available. Also provided in the `X-Plex-Container-Total-Size` header.
         */
        public Builder totalSize(Optional<Long> totalSize) {
            Utils.checkNotNull(totalSize, "totalSize");
            this.totalSize = totalSize;
            return this;
        }


        /**
         * The maximum available bitrate when the decision was rendered.
         */
        public Builder availableBandwidth(long availableBandwidth) {
            Utils.checkNotNull(availableBandwidth, "availableBandwidth");
            this.availableBandwidth = Optional.ofNullable(availableBandwidth);
            return this;
        }

        /**
         * The maximum available bitrate when the decision was rendered.
         */
        public Builder availableBandwidth(Optional<Long> availableBandwidth) {
            Utils.checkNotNull(availableBandwidth, "availableBandwidth");
            this.availableBandwidth = availableBandwidth;
            return this;
        }


        public Builder directPlayDecisionCode(long directPlayDecisionCode) {
            Utils.checkNotNull(directPlayDecisionCode, "directPlayDecisionCode");
            this.directPlayDecisionCode = Optional.ofNullable(directPlayDecisionCode);
            return this;
        }

        public Builder directPlayDecisionCode(Optional<Long> directPlayDecisionCode) {
            Utils.checkNotNull(directPlayDecisionCode, "directPlayDecisionCode");
            this.directPlayDecisionCode = directPlayDecisionCode;
            return this;
        }


        public Builder directPlayDecisionText(String directPlayDecisionText) {
            Utils.checkNotNull(directPlayDecisionText, "directPlayDecisionText");
            this.directPlayDecisionText = Optional.ofNullable(directPlayDecisionText);
            return this;
        }

        public Builder directPlayDecisionText(Optional<String> directPlayDecisionText) {
            Utils.checkNotNull(directPlayDecisionText, "directPlayDecisionText");
            this.directPlayDecisionText = directPlayDecisionText;
            return this;
        }


        /**
         * The overall decision. 1xxx are playback can succeed, 2xxx are a general error (such as insufficient bandwidth), 3xxx are errors in direct play, and 4xxx are errors in transcodes. Same codes are used in all.
         */
        public Builder generalDecisionCode(long generalDecisionCode) {
            Utils.checkNotNull(generalDecisionCode, "generalDecisionCode");
            this.generalDecisionCode = Optional.ofNullable(generalDecisionCode);
            return this;
        }

        /**
         * The overall decision. 1xxx are playback can succeed, 2xxx are a general error (such as insufficient bandwidth), 3xxx are errors in direct play, and 4xxx are errors in transcodes. Same codes are used in all.
         */
        public Builder generalDecisionCode(Optional<Long> generalDecisionCode) {
            Utils.checkNotNull(generalDecisionCode, "generalDecisionCode");
            this.generalDecisionCode = generalDecisionCode;
            return this;
        }


        public Builder generalDecisionText(String generalDecisionText) {
            Utils.checkNotNull(generalDecisionText, "generalDecisionText");
            this.generalDecisionText = Optional.ofNullable(generalDecisionText);
            return this;
        }

        public Builder generalDecisionText(Optional<String> generalDecisionText) {
            Utils.checkNotNull(generalDecisionText, "generalDecisionText");
            this.generalDecisionText = generalDecisionText;
            return this;
        }


        /**
         * The code indicating the status of evaluation of playback when client indicates `hasMDE=1`
         */
        public Builder mdeDecisionCode(long mdeDecisionCode) {
            Utils.checkNotNull(mdeDecisionCode, "mdeDecisionCode");
            this.mdeDecisionCode = Optional.ofNullable(mdeDecisionCode);
            return this;
        }

        /**
         * The code indicating the status of evaluation of playback when client indicates `hasMDE=1`
         */
        public Builder mdeDecisionCode(Optional<Long> mdeDecisionCode) {
            Utils.checkNotNull(mdeDecisionCode, "mdeDecisionCode");
            this.mdeDecisionCode = mdeDecisionCode;
            return this;
        }


        /**
         * Descriptive text for the above code
         */
        public Builder mdeDecisionText(String mdeDecisionText) {
            Utils.checkNotNull(mdeDecisionText, "mdeDecisionText");
            this.mdeDecisionText = Optional.ofNullable(mdeDecisionText);
            return this;
        }

        /**
         * Descriptive text for the above code
         */
        public Builder mdeDecisionText(Optional<String> mdeDecisionText) {
            Utils.checkNotNull(mdeDecisionText, "mdeDecisionText");
            this.mdeDecisionText = mdeDecisionText;
            return this;
        }


        public Builder metadata(List<MediaContainerWithDecisionMetadata> metadata) {
            Utils.checkNotNull(metadata, "metadata");
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        public Builder metadata(Optional<? extends List<MediaContainerWithDecisionMetadata>> metadata) {
            Utils.checkNotNull(metadata, "metadata");
            this.metadata = metadata;
            return this;
        }


        public Builder transcodeDecisionCode(long transcodeDecisionCode) {
            Utils.checkNotNull(transcodeDecisionCode, "transcodeDecisionCode");
            this.transcodeDecisionCode = Optional.ofNullable(transcodeDecisionCode);
            return this;
        }

        public Builder transcodeDecisionCode(Optional<Long> transcodeDecisionCode) {
            Utils.checkNotNull(transcodeDecisionCode, "transcodeDecisionCode");
            this.transcodeDecisionCode = transcodeDecisionCode;
            return this;
        }


        public Builder transcodeDecisionText(String transcodeDecisionText) {
            Utils.checkNotNull(transcodeDecisionText, "transcodeDecisionText");
            this.transcodeDecisionText = Optional.ofNullable(transcodeDecisionText);
            return this;
        }

        public Builder transcodeDecisionText(Optional<String> transcodeDecisionText) {
            Utils.checkNotNull(transcodeDecisionText, "transcodeDecisionText");
            this.transcodeDecisionText = transcodeDecisionText;
            return this;
        }

        public MediaContainerWithDecisionMediaContainer build() {

            return new MediaContainerWithDecisionMediaContainer(
                identifier, offset, size,
                totalSize, availableBandwidth, directPlayDecisionCode,
                directPlayDecisionText, generalDecisionCode, generalDecisionText,
                mdeDecisionCode, mdeDecisionText, metadata,
                transcodeDecisionCode, transcodeDecisionText);
        }

    }
}
