/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.operations.async;

import static dev.plexapi.sdk.operations.Operations.AsyncRequestOperation;

import dev.plexapi.sdk.SDKConfiguration;
import dev.plexapi.sdk.models.operations.AddDeviceRequest;
import dev.plexapi.sdk.operations.AddDevice;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Exception;
import java.util.concurrent.CompletableFuture;

public class AddDeviceRequestBuilder {

    private AddDeviceRequest request;
    private final SDKConfiguration sdkConfiguration;

    public AddDeviceRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public AddDeviceRequestBuilder request(AddDeviceRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<AddDeviceResponse> call() throws Exception {
        
        AsyncRequestOperation<AddDeviceRequest, AddDeviceResponse> operation
              = new AddDevice.Async(sdkConfiguration);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
