/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.operations.async;

import static dev.plexapi.sdk.operations.Operations.AsyncRequestOperation;

import dev.plexapi.sdk.SDKConfiguration;
import dev.plexapi.sdk.models.operations.AddDownloadQueueItemsRequest;
import dev.plexapi.sdk.operations.AddDownloadQueueItems;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Exception;
import java.util.concurrent.CompletableFuture;

public class AddDownloadQueueItemsRequestBuilder {

    private AddDownloadQueueItemsRequest request;
    private final SDKConfiguration sdkConfiguration;

    public AddDownloadQueueItemsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public AddDownloadQueueItemsRequestBuilder request(AddDownloadQueueItemsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<AddDownloadQueueItemsResponse> call() throws Exception {
        
        AsyncRequestOperation<AddDownloadQueueItemsRequest, AddDownloadQueueItemsResponse> operation
              = new AddDownloadQueueItems.Async(sdkConfiguration);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
