/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.operations.async;

import static dev.plexapi.sdk.operations.Operations.AsyncRequestOperation;

import dev.plexapi.sdk.SDKConfiguration;
import dev.plexapi.sdk.models.operations.GetAllSubscriptionsRequest;
import dev.plexapi.sdk.operations.GetAllSubscriptions;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Exception;
import java.util.concurrent.CompletableFuture;

public class GetAllSubscriptionsRequestBuilder {

    private GetAllSubscriptionsRequest request;
    private final SDKConfiguration sdkConfiguration;

    public GetAllSubscriptionsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetAllSubscriptionsRequestBuilder request(GetAllSubscriptionsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<GetAllSubscriptionsResponse> call() throws Exception {
        
        AsyncRequestOperation<GetAllSubscriptionsRequest, GetAllSubscriptionsResponse> operation
              = new GetAllSubscriptions.Async(sdkConfiguration);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
