/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.operations.async;

import static dev.plexapi.sdk.operations.Operations.AsyncRequestOperation;

import dev.plexapi.sdk.SDKConfiguration;
import dev.plexapi.sdk.models.operations.GetDeviceDetailsRequest;
import dev.plexapi.sdk.operations.GetDeviceDetails;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Exception;
import java.util.concurrent.CompletableFuture;

public class GetDeviceDetailsRequestBuilder {

    private GetDeviceDetailsRequest request;
    private final SDKConfiguration sdkConfiguration;

    public GetDeviceDetailsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetDeviceDetailsRequestBuilder request(GetDeviceDetailsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<GetDeviceDetailsResponse> call() throws Exception {
        
        AsyncRequestOperation<GetDeviceDetailsRequest, GetDeviceDetailsResponse> operation
              = new GetDeviceDetails.Async(sdkConfiguration);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
