/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.operations.async;

import static dev.plexapi.sdk.operations.Operations.AsyncRequestOperation;

import dev.plexapi.sdk.SDKConfiguration;
import dev.plexapi.sdk.models.operations.StartBifGenerationRequest;
import dev.plexapi.sdk.operations.StartBifGeneration;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Exception;
import java.util.concurrent.CompletableFuture;

public class StartBifGenerationRequestBuilder {

    private StartBifGenerationRequest request;
    private final SDKConfiguration sdkConfiguration;

    public StartBifGenerationRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public StartBifGenerationRequestBuilder request(StartBifGenerationRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CompletableFuture<StartBifGenerationResponse> call() throws Exception {
        
        AsyncRequestOperation<StartBifGenerationRequest, StartBifGenerationResponse> operation
              = new StartBifGeneration.Async(sdkConfiguration);

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
