/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk;

import static dev.plexapi.sdk.operations.Operations.AsyncRequestOperation;

import dev.plexapi.sdk.models.operations.AddCollectionItemsRequest;
import dev.plexapi.sdk.models.operations.DeleteCollectionItemRequest;
import dev.plexapi.sdk.models.operations.MoveCollectionItemRequest;
import dev.plexapi.sdk.models.operations.async.AddCollectionItemsRequestBuilder;
import dev.plexapi.sdk.models.operations.async.AddCollectionItemsResponse;
import dev.plexapi.sdk.models.operations.async.DeleteCollectionItemRequestBuilder;
import dev.plexapi.sdk.models.operations.async.DeleteCollectionItemResponse;
import dev.plexapi.sdk.models.operations.async.MoveCollectionItemRequestBuilder;
import dev.plexapi.sdk.models.operations.async.MoveCollectionItemResponse;
import dev.plexapi.sdk.operations.AddCollectionItems;
import dev.plexapi.sdk.operations.DeleteCollectionItem;
import dev.plexapi.sdk.operations.MoveCollectionItem;
import java.util.concurrent.CompletableFuture;

/**
 * Endpoints for manipulating collections.  In addition to these endpoints, `/library/collections/:collectionId/X` will be rerouted to `/library/metadata/:collectionId/X` and respond to those endpoints as well.
 */
public class AsyncLibraryCollections {
    private final SDKConfiguration sdkConfiguration;
    private final LibraryCollections syncSDK;

    AsyncLibraryCollections(LibraryCollections syncSDK, SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.syncSDK = syncSDK;
    }

    /**
     * Switches to the sync SDK.
     * 
     * @return The sync SDK
     */
    public LibraryCollections sync() {
        return syncSDK;
    }


    /**
     * Add items to a collection
     * 
     * <p>Add items to a collection by uri
     * 
     * @return The async call builder
     */
    public AddCollectionItemsRequestBuilder addCollectionItems() {
        return new AddCollectionItemsRequestBuilder(sdkConfiguration);
    }

    /**
     * Add items to a collection
     * 
     * <p>Add items to a collection by uri
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return CompletableFuture&lt;AddCollectionItemsResponse&gt; - The async response
     */
    public CompletableFuture<AddCollectionItemsResponse> addCollectionItems(AddCollectionItemsRequest request) {
        AsyncRequestOperation<AddCollectionItemsRequest, AddCollectionItemsResponse> operation
              = new AddCollectionItems.Async(sdkConfiguration);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Delete an item from a collection
     * 
     * <p>Delete an item from a collection
     * 
     * @return The async call builder
     */
    public DeleteCollectionItemRequestBuilder deleteCollectionItem() {
        return new DeleteCollectionItemRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete an item from a collection
     * 
     * <p>Delete an item from a collection
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return CompletableFuture&lt;DeleteCollectionItemResponse&gt; - The async response
     */
    public CompletableFuture<DeleteCollectionItemResponse> deleteCollectionItem(DeleteCollectionItemRequest request) {
        AsyncRequestOperation<DeleteCollectionItemRequest, DeleteCollectionItemResponse> operation
              = new DeleteCollectionItem.Async(sdkConfiguration);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }


    /**
     * Reorder an item in the collection
     * 
     * <p>Reorder items in a collection with one item after another
     * 
     * @return The async call builder
     */
    public MoveCollectionItemRequestBuilder moveCollectionItem() {
        return new MoveCollectionItemRequestBuilder(sdkConfiguration);
    }

    /**
     * Reorder an item in the collection
     * 
     * <p>Reorder items in a collection with one item after another
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return CompletableFuture&lt;MoveCollectionItemResponse&gt; - The async response
     */
    public CompletableFuture<MoveCollectionItemResponse> moveCollectionItem(MoveCollectionItemRequest request) {
        AsyncRequestOperation<MoveCollectionItemRequest, MoveCollectionItemResponse> operation
              = new MoveCollectionItem.Async(sdkConfiguration);
        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }

}
