/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk;

import static dev.plexapi.sdk.operations.Operations.RequestOperation;

import dev.plexapi.sdk.models.operations.ConnectWebSocketRequest;
import dev.plexapi.sdk.models.operations.ConnectWebSocketRequestBuilder;
import dev.plexapi.sdk.models.operations.ConnectWebSocketResponse;
import dev.plexapi.sdk.models.operations.GetNotificationsRequest;
import dev.plexapi.sdk.models.operations.GetNotificationsRequestBuilder;
import dev.plexapi.sdk.models.operations.GetNotificationsResponse;
import dev.plexapi.sdk.operations.ConnectWebSocket;
import dev.plexapi.sdk.operations.GetNotifications;
import java.lang.Exception;

/**
 * The server can notify clients in real-time of a wide range of events, from library scanning, to preferences being modified, to changes to media, and many other things. This is also the mechanism by which activity progress is reported.
 * 
 * <p>Two protocols for receiving the events are available: EventSource (also known as SSE), and WebSocket.
 */
public class Events {
    private final SDKConfiguration sdkConfiguration;
    private final AsyncEvents asyncSDK;

    Events(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncEvents(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncEvents async() {
        return asyncSDK;
    }

    /**
     * Connect to Eventsource
     * 
     * <p>Connect to the event source to get a stream of events
     * 
     * @return The call builder
     */
    public GetNotificationsRequestBuilder getNotifications() {
        return new GetNotificationsRequestBuilder(sdkConfiguration);
    }

    /**
     * Connect to Eventsource
     * 
     * <p>Connect to the event source to get a stream of events
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public GetNotificationsResponse getNotifications(GetNotificationsRequest request) throws Exception {
        RequestOperation<GetNotificationsRequest, GetNotificationsResponse> operation
              = new GetNotifications.Sync(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Connect to WebSocket
     * 
     * <p>Connect to the web socket to get a stream of events
     * 
     * @return The call builder
     */
    public ConnectWebSocketRequestBuilder connectWebSocket() {
        return new ConnectWebSocketRequestBuilder(sdkConfiguration);
    }

    /**
     * Connect to WebSocket
     * 
     * <p>Connect to the web socket to get a stream of events
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ConnectWebSocketResponse connectWebSocket(ConnectWebSocketRequest request) throws Exception {
        RequestOperation<ConnectWebSocketRequest, ConnectWebSocketResponse> operation
              = new ConnectWebSocket.Sync(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(request));
    }

}
