workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    plexapi:
        inputs:
            - location: https://raw.githubusercontent.com/LukeHagar/plex-api-spec/refs/heads/main/plex-api-spec.yaml
        registry:
            location: registry.speakeasyapi.dev/plexapi/plexapi/plexapi
targets:
    plexjava:
        target: java
        source: plexapi
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/plexapi/plexapi/code-samples-java-plexjava
            labelOverride:
                fixedValue: PlexJava
