workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    plexapi:
        inputs:
            - location: registry.speakeasyapi.dev/plexapi/plexapi/plexapi:main
targets:
    plexjava:
        target: java
        source: plexapi
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            labelOverride: 
                fixedValue: PlexJava
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/plexapi/plexapi/code-samples-java-plexjava
