/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.operations;

import static dev.plexapi.sdk.operations.Operations.RequestOperation;

import dev.plexapi.sdk.SDKConfiguration;
import dev.plexapi.sdk.operations.AddToPlayQueue;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Exception;

public class AddToPlayQueueRequestBuilder {

    private AddToPlayQueueRequest request;
    private final SDKConfiguration sdkConfiguration;

    public AddToPlayQueueRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public AddToPlayQueueRequestBuilder request(AddToPlayQueueRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public AddToPlayQueueResponse call() throws Exception {
        
        RequestOperation<AddToPlayQueueRequest, AddToPlayQueueResponse> operation
              = new AddToPlayQueue.Sync(sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
