/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Objects;
import java.util.Optional;

/**
 * ChromaSubsampling
 * 
 * <p>Use the specified chroma subsambling.
 *   - 0: 411
 *   - 1: 420
 *   - 2: 422
 *   - 3: 444
 * Defaults to 3 (444)
 */
public enum ChromaSubsampling {
    ZERO(0L),
    ONE(1L),
    TWO(2L),
    THREE(3L);

    @JsonValue
    private final long value;

    ChromaSubsampling(long value) {
        this.value = value;
    }
    
    public long value() {
        return value;
    }
    
    public static Optional<ChromaSubsampling> fromValue(long value) {
        for (ChromaSubsampling o: ChromaSubsampling.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

