/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class Country {
    /**
     * Three letter code
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("code")
    private Optional<String> code;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("example")
    private Optional<String> example;

    /**
     * - `0`: The country is divided into regions, and following the key will lead to a list of regions.
     * - `1`: The county is divided by postal codes, and an example code is returned in `example`.
     * - `2`: The country has a single postal code, returned in `example`.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("flavor")
    private Optional<? extends Flavor> flavor;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("key")
    private Optional<String> key;

    /**
     * Three letter language code
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("language")
    private Optional<String> language;

    /**
     * The title of the language
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("languageTitle")
    private Optional<String> languageTitle;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("title")
    private Optional<String> title;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private Optional<String> type;

    @JsonCreator
    public Country(
            @JsonProperty("code") Optional<String> code,
            @JsonProperty("example") Optional<String> example,
            @JsonProperty("flavor") Optional<? extends Flavor> flavor,
            @JsonProperty("key") Optional<String> key,
            @JsonProperty("language") Optional<String> language,
            @JsonProperty("languageTitle") Optional<String> languageTitle,
            @JsonProperty("title") Optional<String> title,
            @JsonProperty("type") Optional<String> type) {
        Utils.checkNotNull(code, "code");
        Utils.checkNotNull(example, "example");
        Utils.checkNotNull(flavor, "flavor");
        Utils.checkNotNull(key, "key");
        Utils.checkNotNull(language, "language");
        Utils.checkNotNull(languageTitle, "languageTitle");
        Utils.checkNotNull(title, "title");
        Utils.checkNotNull(type, "type");
        this.code = code;
        this.example = example;
        this.flavor = flavor;
        this.key = key;
        this.language = language;
        this.languageTitle = languageTitle;
        this.title = title;
        this.type = type;
    }
    
    public Country() {
        this(Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty());
    }

    /**
     * Three letter code
     */
    @JsonIgnore
    public Optional<String> code() {
        return code;
    }

    @JsonIgnore
    public Optional<String> example() {
        return example;
    }

    /**
     * - `0`: The country is divided into regions, and following the key will lead to a list of regions.
     * - `1`: The county is divided by postal codes, and an example code is returned in `example`.
     * - `2`: The country has a single postal code, returned in `example`.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Flavor> flavor() {
        return (Optional<Flavor>) flavor;
    }

    @JsonIgnore
    public Optional<String> key() {
        return key;
    }

    /**
     * Three letter language code
     */
    @JsonIgnore
    public Optional<String> language() {
        return language;
    }

    /**
     * The title of the language
     */
    @JsonIgnore
    public Optional<String> languageTitle() {
        return languageTitle;
    }

    @JsonIgnore
    public Optional<String> title() {
        return title;
    }

    @JsonIgnore
    public Optional<String> type() {
        return type;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Three letter code
     */
    public Country withCode(String code) {
        Utils.checkNotNull(code, "code");
        this.code = Optional.ofNullable(code);
        return this;
    }


    /**
     * Three letter code
     */
    public Country withCode(Optional<String> code) {
        Utils.checkNotNull(code, "code");
        this.code = code;
        return this;
    }

    public Country withExample(String example) {
        Utils.checkNotNull(example, "example");
        this.example = Optional.ofNullable(example);
        return this;
    }


    public Country withExample(Optional<String> example) {
        Utils.checkNotNull(example, "example");
        this.example = example;
        return this;
    }

    /**
     * - `0`: The country is divided into regions, and following the key will lead to a list of regions.
     * - `1`: The county is divided by postal codes, and an example code is returned in `example`.
     * - `2`: The country has a single postal code, returned in `example`.
     */
    public Country withFlavor(Flavor flavor) {
        Utils.checkNotNull(flavor, "flavor");
        this.flavor = Optional.ofNullable(flavor);
        return this;
    }


    /**
     * - `0`: The country is divided into regions, and following the key will lead to a list of regions.
     * - `1`: The county is divided by postal codes, and an example code is returned in `example`.
     * - `2`: The country has a single postal code, returned in `example`.
     */
    public Country withFlavor(Optional<? extends Flavor> flavor) {
        Utils.checkNotNull(flavor, "flavor");
        this.flavor = flavor;
        return this;
    }

    public Country withKey(String key) {
        Utils.checkNotNull(key, "key");
        this.key = Optional.ofNullable(key);
        return this;
    }


    public Country withKey(Optional<String> key) {
        Utils.checkNotNull(key, "key");
        this.key = key;
        return this;
    }

    /**
     * Three letter language code
     */
    public Country withLanguage(String language) {
        Utils.checkNotNull(language, "language");
        this.language = Optional.ofNullable(language);
        return this;
    }


    /**
     * Three letter language code
     */
    public Country withLanguage(Optional<String> language) {
        Utils.checkNotNull(language, "language");
        this.language = language;
        return this;
    }

    /**
     * The title of the language
     */
    public Country withLanguageTitle(String languageTitle) {
        Utils.checkNotNull(languageTitle, "languageTitle");
        this.languageTitle = Optional.ofNullable(languageTitle);
        return this;
    }


    /**
     * The title of the language
     */
    public Country withLanguageTitle(Optional<String> languageTitle) {
        Utils.checkNotNull(languageTitle, "languageTitle");
        this.languageTitle = languageTitle;
        return this;
    }

    public Country withTitle(String title) {
        Utils.checkNotNull(title, "title");
        this.title = Optional.ofNullable(title);
        return this;
    }


    public Country withTitle(Optional<String> title) {
        Utils.checkNotNull(title, "title");
        this.title = title;
        return this;
    }

    public Country withType(String type) {
        Utils.checkNotNull(type, "type");
        this.type = Optional.ofNullable(type);
        return this;
    }


    public Country withType(Optional<String> type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Country other = (Country) o;
        return 
            Utils.enhancedDeepEquals(this.code, other.code) &&
            Utils.enhancedDeepEquals(this.example, other.example) &&
            Utils.enhancedDeepEquals(this.flavor, other.flavor) &&
            Utils.enhancedDeepEquals(this.key, other.key) &&
            Utils.enhancedDeepEquals(this.language, other.language) &&
            Utils.enhancedDeepEquals(this.languageTitle, other.languageTitle) &&
            Utils.enhancedDeepEquals(this.title, other.title) &&
            Utils.enhancedDeepEquals(this.type, other.type);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            code, example, flavor,
            key, language, languageTitle,
            title, type);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Country.class,
                "code", code,
                "example", example,
                "flavor", flavor,
                "key", key,
                "language", language,
                "languageTitle", languageTitle,
                "title", title,
                "type", type);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> code = Optional.empty();

        private Optional<String> example = Optional.empty();

        private Optional<? extends Flavor> flavor = Optional.empty();

        private Optional<String> key = Optional.empty();

        private Optional<String> language = Optional.empty();

        private Optional<String> languageTitle = Optional.empty();

        private Optional<String> title = Optional.empty();

        private Optional<String> type = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Three letter code
         */
        public Builder code(String code) {
            Utils.checkNotNull(code, "code");
            this.code = Optional.ofNullable(code);
            return this;
        }

        /**
         * Three letter code
         */
        public Builder code(Optional<String> code) {
            Utils.checkNotNull(code, "code");
            this.code = code;
            return this;
        }


        public Builder example(String example) {
            Utils.checkNotNull(example, "example");
            this.example = Optional.ofNullable(example);
            return this;
        }

        public Builder example(Optional<String> example) {
            Utils.checkNotNull(example, "example");
            this.example = example;
            return this;
        }


        /**
         * - `0`: The country is divided into regions, and following the key will lead to a list of regions.
         * - `1`: The county is divided by postal codes, and an example code is returned in `example`.
         * - `2`: The country has a single postal code, returned in `example`.
         */
        public Builder flavor(Flavor flavor) {
            Utils.checkNotNull(flavor, "flavor");
            this.flavor = Optional.ofNullable(flavor);
            return this;
        }

        /**
         * - `0`: The country is divided into regions, and following the key will lead to a list of regions.
         * - `1`: The county is divided by postal codes, and an example code is returned in `example`.
         * - `2`: The country has a single postal code, returned in `example`.
         */
        public Builder flavor(Optional<? extends Flavor> flavor) {
            Utils.checkNotNull(flavor, "flavor");
            this.flavor = flavor;
            return this;
        }


        public Builder key(String key) {
            Utils.checkNotNull(key, "key");
            this.key = Optional.ofNullable(key);
            return this;
        }

        public Builder key(Optional<String> key) {
            Utils.checkNotNull(key, "key");
            this.key = key;
            return this;
        }


        /**
         * Three letter language code
         */
        public Builder language(String language) {
            Utils.checkNotNull(language, "language");
            this.language = Optional.ofNullable(language);
            return this;
        }

        /**
         * Three letter language code
         */
        public Builder language(Optional<String> language) {
            Utils.checkNotNull(language, "language");
            this.language = language;
            return this;
        }


        /**
         * The title of the language
         */
        public Builder languageTitle(String languageTitle) {
            Utils.checkNotNull(languageTitle, "languageTitle");
            this.languageTitle = Optional.ofNullable(languageTitle);
            return this;
        }

        /**
         * The title of the language
         */
        public Builder languageTitle(Optional<String> languageTitle) {
            Utils.checkNotNull(languageTitle, "languageTitle");
            this.languageTitle = languageTitle;
            return this;
        }


        public Builder title(String title) {
            Utils.checkNotNull(title, "title");
            this.title = Optional.ofNullable(title);
            return this;
        }

        public Builder title(Optional<String> title) {
            Utils.checkNotNull(title, "title");
            this.title = title;
            return this;
        }


        public Builder type(String type) {
            Utils.checkNotNull(type, "type");
            this.type = Optional.ofNullable(type);
            return this;
        }

        public Builder type(Optional<String> type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }

        public Country build() {

            return new Country(
                code, example, flavor,
                key, language, languageTitle,
                title, type);
        }

    }
}
