/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.operations;

import static dev.plexapi.sdk.operations.Operations.RequestlessOperation;

import dev.plexapi.sdk.SDKConfiguration;
import dev.plexapi.sdk.operations.GetAllLanguages;
import java.lang.Exception;

public class GetAllLanguagesRequestBuilder {

    private final SDKConfiguration sdkConfiguration;

    public GetAllLanguagesRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetAllLanguagesResponse call() throws Exception {
        
        RequestlessOperation<GetAllLanguagesResponse> operation
            = new GetAllLanguages.Sync(sdkConfiguration);

        return operation.handleResponse(operation.doRequest());
    }
}
