/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * GetLibrarySectionsAllMeta
 * 
 * <p>The Meta object is only included in the response if the `includeMeta` parameter is set to `1`.
 */
public class GetLibrarySectionsAllMeta {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("Type")
    private Optional<? extends List<GetLibrarySectionsAllType>> type;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("FieldType")
    private Optional<? extends List<GetLibrarySectionsAllFieldType>> fieldType;

    @JsonCreator
    public GetLibrarySectionsAllMeta(
            @JsonProperty("Type") Optional<? extends List<GetLibrarySectionsAllType>> type,
            @JsonProperty("FieldType") Optional<? extends List<GetLibrarySectionsAllFieldType>> fieldType) {
        Utils.checkNotNull(type, "type");
        Utils.checkNotNull(fieldType, "fieldType");
        this.type = type;
        this.fieldType = fieldType;
    }
    
    public GetLibrarySectionsAllMeta() {
        this(Optional.empty(), Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<GetLibrarySectionsAllType>> type() {
        return (Optional<List<GetLibrarySectionsAllType>>) type;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<GetLibrarySectionsAllFieldType>> fieldType() {
        return (Optional<List<GetLibrarySectionsAllFieldType>>) fieldType;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public GetLibrarySectionsAllMeta withType(List<GetLibrarySectionsAllType> type) {
        Utils.checkNotNull(type, "type");
        this.type = Optional.ofNullable(type);
        return this;
    }

    public GetLibrarySectionsAllMeta withType(Optional<? extends List<GetLibrarySectionsAllType>> type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
        return this;
    }

    public GetLibrarySectionsAllMeta withFieldType(List<GetLibrarySectionsAllFieldType> fieldType) {
        Utils.checkNotNull(fieldType, "fieldType");
        this.fieldType = Optional.ofNullable(fieldType);
        return this;
    }

    public GetLibrarySectionsAllMeta withFieldType(Optional<? extends List<GetLibrarySectionsAllFieldType>> fieldType) {
        Utils.checkNotNull(fieldType, "fieldType");
        this.fieldType = fieldType;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetLibrarySectionsAllMeta other = (GetLibrarySectionsAllMeta) o;
        return 
            Objects.deepEquals(this.type, other.type) &&
            Objects.deepEquals(this.fieldType, other.fieldType);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            type,
            fieldType);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetLibrarySectionsAllMeta.class,
                "type", type,
                "fieldType", fieldType);
    }
    
    public final static class Builder {
 
        private Optional<? extends List<GetLibrarySectionsAllType>> type = Optional.empty();
 
        private Optional<? extends List<GetLibrarySectionsAllFieldType>> fieldType = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder type(List<GetLibrarySectionsAllType> type) {
            Utils.checkNotNull(type, "type");
            this.type = Optional.ofNullable(type);
            return this;
        }

        public Builder type(Optional<? extends List<GetLibrarySectionsAllType>> type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }

        public Builder fieldType(List<GetLibrarySectionsAllFieldType> fieldType) {
            Utils.checkNotNull(fieldType, "fieldType");
            this.fieldType = Optional.ofNullable(fieldType);
            return this;
        }

        public Builder fieldType(Optional<? extends List<GetLibrarySectionsAllFieldType>> fieldType) {
            Utils.checkNotNull(fieldType, "fieldType");
            this.fieldType = fieldType;
            return this;
        }
        
        public GetLibrarySectionsAllMeta build() {
            return new GetLibrarySectionsAllMeta(
                type,
                fieldType);
        }
    }
}
