/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.operations;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * <p>Wrapper class for an "open" enum. "Open" enums are those that are expected
 * to evolve (particularly with the addition of enum members over time). If an
 * open enum is used then the appearance of unexpected enum values (say in a 
 * response from an updated an API) will not bring about a runtime error thus 
 * ensuring that non-updated client versions can continue to work without error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe
 * cache is maintained to ensure that). As a consequence instances created with the 
 * same value will satisfy reference equality (via {@code ==}).
 * 
 * <p>This class is intended to emulate an enum (in terms of common usage and with 
 * reference equality) but with the ability to carry unknown values. Unfortunately
 * Java does not permit the use of an instance in a switch expression but you can 
 * use the {@code asEnum()} method (after dealing with the `Optional` appropriately).
 *
 */
/**
 * GetPlaylistContentsQueryParamType
 * 
 * <p>The type of media to retrieve or filter by.
 * 1 = movie
 * 2 = show
 * 3 = season
 * 4 = episode
 * E.g. A movie library will not return anything with type 3 as there are no seasons for movie libraries
 */
@JsonDeserialize(using = GetPlaylistContentsQueryParamType._Deserializer.class)
@JsonSerialize(using = GetPlaylistContentsQueryParamType._Serializer.class)
public class GetPlaylistContentsQueryParamType {

    public static final GetPlaylistContentsQueryParamType Movie = new GetPlaylistContentsQueryParamType(1L);
    public static final GetPlaylistContentsQueryParamType TvShow = new GetPlaylistContentsQueryParamType(2L);
    public static final GetPlaylistContentsQueryParamType Season = new GetPlaylistContentsQueryParamType(3L);
    public static final GetPlaylistContentsQueryParamType Episode = new GetPlaylistContentsQueryParamType(4L);
    public static final GetPlaylistContentsQueryParamType Artist = new GetPlaylistContentsQueryParamType(5L);
    public static final GetPlaylistContentsQueryParamType Album = new GetPlaylistContentsQueryParamType(6L);
    public static final GetPlaylistContentsQueryParamType Track = new GetPlaylistContentsQueryParamType(7L);
    public static final GetPlaylistContentsQueryParamType PhotoAlbum = new GetPlaylistContentsQueryParamType(8L);
    public static final GetPlaylistContentsQueryParamType Photo = new GetPlaylistContentsQueryParamType(9L);

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<Long, GetPlaylistContentsQueryParamType> values = createValuesMap();
    private static final Map<Long, GetPlaylistContentsQueryParamTypeEnum> enums = createEnumsMap();

    private final long value;

    private GetPlaylistContentsQueryParamType(long value) {
        this.value = value;
    }

    /**
     * Returns a GetPlaylistContentsQueryParamType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as GetPlaylistContentsQueryParamType
     */ 
    public static GetPlaylistContentsQueryParamType of(long value) {
        synchronized (GetPlaylistContentsQueryParamType.class) {
            return values.computeIfAbsent(value, v -> new GetPlaylistContentsQueryParamType(v));
        }
    }

    public long value() {
        return value;
    }

    public Optional<GetPlaylistContentsQueryParamTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        GetPlaylistContentsQueryParamType other = (GetPlaylistContentsQueryParamType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "GetPlaylistContentsQueryParamType [value=" + value + "]";
    }

    // return an array just like an enum
    public static GetPlaylistContentsQueryParamType[] values() {
        synchronized (GetPlaylistContentsQueryParamType.class) {
            return values.values().toArray(new GetPlaylistContentsQueryParamType[] {});
        }
    }

    private static final Map<Long, GetPlaylistContentsQueryParamType> createValuesMap() {
        Map<Long, GetPlaylistContentsQueryParamType> map = new LinkedHashMap<>();
        map.put(1L, Movie);
        map.put(2L, TvShow);
        map.put(3L, Season);
        map.put(4L, Episode);
        map.put(5L, Artist);
        map.put(6L, Album);
        map.put(7L, Track);
        map.put(8L, PhotoAlbum);
        map.put(9L, Photo);
        return map;
    }

    private static final Map<Long, GetPlaylistContentsQueryParamTypeEnum> createEnumsMap() {
        Map<Long, GetPlaylistContentsQueryParamTypeEnum> map = new HashMap<>();
        map.put(1L, GetPlaylistContentsQueryParamTypeEnum.Movie);
        map.put(2L, GetPlaylistContentsQueryParamTypeEnum.TvShow);
        map.put(3L, GetPlaylistContentsQueryParamTypeEnum.Season);
        map.put(4L, GetPlaylistContentsQueryParamTypeEnum.Episode);
        map.put(5L, GetPlaylistContentsQueryParamTypeEnum.Artist);
        map.put(6L, GetPlaylistContentsQueryParamTypeEnum.Album);
        map.put(7L, GetPlaylistContentsQueryParamTypeEnum.Track);
        map.put(8L, GetPlaylistContentsQueryParamTypeEnum.PhotoAlbum);
        map.put(9L, GetPlaylistContentsQueryParamTypeEnum.Photo);
        return map;
    }
    
    @SuppressWarnings("serial")
    public static final class _Serializer extends StdSerializer<GetPlaylistContentsQueryParamType> {

        protected _Serializer() {
            super(GetPlaylistContentsQueryParamType.class);
        }

        @Override
        public void serialize(GetPlaylistContentsQueryParamType value, JsonGenerator g, SerializerProvider provider)
                throws IOException, JsonProcessingException {
            g.writeObject(value.value);
        }
    }

    @SuppressWarnings("serial")
    public static final class _Deserializer extends StdDeserializer<GetPlaylistContentsQueryParamType> {

        protected _Deserializer() {
            super(GetPlaylistContentsQueryParamType.class);
        }

        @Override
        public GetPlaylistContentsQueryParamType deserialize(JsonParser p, DeserializationContext ctxt)
                throws IOException, JacksonException {
            long v = p.readValueAs(new TypeReference<Long>() {});
            // use the factory method to ensure we get singletons
            return GetPlaylistContentsQueryParamType.of(v);
        }
    }
    
    public enum GetPlaylistContentsQueryParamTypeEnum {

        Movie(1L),
        TvShow(2L),
        Season(3L),
        Episode(4L),
        Artist(5L),
        Album(6L),
        Track(7L),
        PhotoAlbum(8L),
        Photo(9L),;

        private final long value;

        private GetPlaylistContentsQueryParamTypeEnum(long value) {
            this.value = value;
        }

        public long value() {
            return value;
        }
    }
}

