/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package dev.plexapi.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import dev.plexapi.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;

/**
 * GetSectionHubsResponseBody
 * 
 * <p>OK
 */
public class GetSectionHubsResponseBody {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("MediaContainer")
    private Optional<? extends GetSectionHubsMediaContainer> mediaContainer;

    @JsonCreator
    public GetSectionHubsResponseBody(
            @JsonProperty("MediaContainer") Optional<? extends GetSectionHubsMediaContainer> mediaContainer) {
        Utils.checkNotNull(mediaContainer, "mediaContainer");
        this.mediaContainer = mediaContainer;
    }
    
    public GetSectionHubsResponseBody() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<GetSectionHubsMediaContainer> mediaContainer() {
        return (Optional<GetSectionHubsMediaContainer>) mediaContainer;
    }

    public static Builder builder() {
        return new Builder();
    }


    public GetSectionHubsResponseBody withMediaContainer(GetSectionHubsMediaContainer mediaContainer) {
        Utils.checkNotNull(mediaContainer, "mediaContainer");
        this.mediaContainer = Optional.ofNullable(mediaContainer);
        return this;
    }


    public GetSectionHubsResponseBody withMediaContainer(Optional<? extends GetSectionHubsMediaContainer> mediaContainer) {
        Utils.checkNotNull(mediaContainer, "mediaContainer");
        this.mediaContainer = mediaContainer;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetSectionHubsResponseBody other = (GetSectionHubsResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.mediaContainer, other.mediaContainer);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            mediaContainer);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetSectionHubsResponseBody.class,
                "mediaContainer", mediaContainer);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends GetSectionHubsMediaContainer> mediaContainer = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder mediaContainer(GetSectionHubsMediaContainer mediaContainer) {
            Utils.checkNotNull(mediaContainer, "mediaContainer");
            this.mediaContainer = Optional.ofNullable(mediaContainer);
            return this;
        }

        public Builder mediaContainer(Optional<? extends GetSectionHubsMediaContainer> mediaContainer) {
            Utils.checkNotNull(mediaContainer, "mediaContainer");
            this.mediaContainer = mediaContainer;
            return this;
        }

        public GetSectionHubsResponseBody build() {

            return new GetSectionHubsResponseBody(
                mediaContainer);
        }

    }
}
