/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.plexapi.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * QueryParamSmart - type of playlists to return (default is all).
 */
public enum QueryParamSmart {
    ZERO(0L),
    ONE(1L);

    @JsonValue
    private final long value;

    private QueryParamSmart(long value) {
        this.value = value;
    }
    
    public long value() {
        return value;
    }
}
