/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package dev.plexapi.sdk;

import dev.plexapi.sdk.models.operations.Filter;
import dev.plexapi.sdk.models.operations.GetWatchListRequest;
import dev.plexapi.sdk.models.operations.GetWatchListResponse;
import java.lang.Exception;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

public class WatchlistTests { 

    @Disabled // test marked as skipped for java or generated unit tests not production ready yet
    @Test
    public void testWatchlist_GetWatchList() throws Exception {


        PlexAPI sdk = PlexAPI.builder()
                .accessToken("<YOUR_API_KEY_HERE>")
                .clientID("gcgzw5rz2xovp84b4vha3a40")
                .clientName("Plex Web")
                .clientVersion("4.133.0")
                .clientPlatform("Chrome")
                .deviceName("Linux")
            .build();

        GetWatchListRequest req = GetWatchListRequest.builder()
                .filter(Filter.RELEASED)
                .xPlexToken("CV5xoxjTpFKUzBTShsaf")
                .xPlexContainerStart(0)
                .xPlexContainerSize(50)
                .build();

        GetWatchListResponse res = sdk.watchlist().getWatchList()
                .request(req)
                .call();


    }

}